/* eslint-disable react/jsx-key */
/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from "../styles/Home.module.css"
import { useState } from 'react';
import { roles } from "../data";

const activeState = `${styles.revealWrapper} ${styles.show} ${styles.aOn}`;
const deactiveState = `${styles.revealWrapper} ${styles.hide} ${styles.aOff}`;

const showState = `${styles.jobTitleRoot} ${styles.jobTitleShow}`;

const Home: NextPage = () => {
  const [selectedRole, setSelectedRole] = useState(0);
  const [activeSkill, setActiveSkill] = useState(0)
  return (
    <>
      <Head>
        <title>Final Fantasy XIV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </Head>

      <section className={styles.container}>
        <div className={styles.header}>
          <div className={styles.pageTitleRoot}>
            <h1>
              <div className={styles.revealFromDownside}>
                <span className={styles.intro}>
                  Pick your
                </span>
              </div>

              <div className={styles.revealFromUpside}>
                <span className={styles.title}>
                  job
                </span>
              </div>
            </h1>

            <p className={styles.description}>
              Que vous souhaitiez foncer dans la mêlée, soutenir vos alliés ou trouver un entre-deux, vous trouverez forcément votre bonheur dans la Faille.
            </p>
          </div>
        </div>
        <div className={styles.selector}>
          <nav className={styles.jobSelectorRoot}>
            {roles.map(({ id, role }, index) => {
              return (
                <div
                  key={id}
                  className={index === selectedRole ? `${styles.jobSelectorButton} ${styles.jobSelectorIsActive}` : styles.jobSelectorButton}
                  onClick={() => setSelectedRole(index)}
                >
                  {role}
                </div>
              )
            })}
          </nav>
        </div>
        <div className={styles.preview}>
          <div className={styles.jobPreview}>
            {roles.map(({ img, id, role, description, icon, skills, char, background }, index) => {
              return (
                <div
                  key={id}
                  className={index === selectedRole ? activeState : deactiveState}
                  style={{ position: "absolute" }}
                >
                  {/* BACKGROUND */}
                  <div style={{ background: `url("https://www.transparenttextures.com/patterns/black-twill.png"), url(${background})` }} className={styles.championBackground} />

                  {/* CHARACTER */}
                  <figure className={styles.championFigure}>
                    <img className={styles.championImageChar} src={char} alt="alt" />
                  </figure>


                  <div style={{display: "flex", position: "absolute", width: "100%", height: "100%", justifyContent: "center"}}>
                    {/* INFO JOB */}
                    <div className={styles.jobTitleRoot}>
                      <div style={{ display: "flex", alignContent: "center" }}>
                        <img style={{ height: "60px" }} src={icon} />
                        <p style={{ display: "flex", alignContent: "center" }} className={styles.jobTitle}>
                          {role}
                        </p>
                      </div>
                      <p className={styles.jobDescription}>
                        {description}
                      </p>
                      <div className={styles.spellSelector}>
                        {roles[selectedRole].skills.map((skill, index) => {
                          return (
                            <div className={activeSkill === index? `${styles.cardSkill} ${styles.cardSkillActive}`: styles.cardSkill} onClick={() => setActiveSkill(index)}>
                              <img style={{height: "100%", width: "100%", objectFit: "contain"}} src={skill.icon} />
                            </div>
                          )
                        })}
                      </div>
                    </div>

                    {/* SKILL DETAIL */}
                    <div className={styles.rootSkill}>
                      <div className={styles.topSkill}>
                        <div className={styles.colLeft}>
                          <img src={skills[activeSkill].icon} />
                        </div>
                        <div className={styles.colRight}>
                          <p className={styles.skillName}>{skills[activeSkill].name}</p>
                          <p className={styles.skillLevel}>{skills[activeSkill].effect}</p>
                        </div>
                      </div>
                      <div className={styles.botSkill}>
                        <div>Mana : {skills[activeSkill].cost}</div>
                        <div>Cast : {skills[activeSkill].recast}</div>
                      </div>
                      {/* <p className={styles.skillLevel}>{skills[activeSkill].level}</p> */}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </>
  )
}

export default Home
